name: Deploy

on:
  push:
    branches:
      - main
      - james/init
  workflow_dispatch:

permissions: read-all

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_to_dev3:
    name: Deploy to dev 3
    uses: ./.github/workflows/deploy-to-k8s.yaml
    with:
      environment: dev3
    secrets: inherit
    # if: github.ref == 'refs/heads/main'

  deploy_to_prod3:
    name: Deploy to prod 3
    uses: ./.github/workflows/deploy-to-k8s.yaml
    with:
      environment: prod3
    secrets: inherit
    needs: deploy_to_dev3
    if: github.ref == 'refs/heads/main'
